# Generated by Django 5.2.9 on 2026-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
