# Generated by Django 5.2.13 on 2026-05-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='author_name_gin_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='magazinearticle',
            name='article_title_gin_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_name_gin_trgm_idx',
        ),
    ]
